### ISSUE TITLE
Pb with rts

### ISSUE THREAD

**Issue by mupfpilou** [Doubledom45/HA-2024.3-RFPLAYER#2]
Hello

I have 2 issues with the new version

1/
Sometimes after ha reboot, device need to be configure again, and it needs another ha reboot

2/
I have 3 Somfy rts cover
Since the new version, the DIM command is not working anymore on the created entity
If i do a manual send command, its ok
How can we fix ?

Thx

**Comment by Doubledom45** [comment]
Slt.
Pour le RTS , il me faut les log en debug.
En manuel comment est le YAML ?

**Comment by mupfpilou** [comment]
J'ai essayé de créer une nouvelle entité pdt que j'appelais le service DIM
La nouvelle entité fonctionne correctement

Comment je vois le yaml en manuel ? Il est dans le dossier custom_components ?
Comment je peux retirer des entités que je ne veux plus ?

Merci

**Comment by Doubledom45** [comment]
>Comment je vois le yaml en manuel ? Il est dans le dossier custom_components ?

## Oui dans `custom_components/rfplayer/rflib/rfpprotocol.py`

>Comment je peux retirer des entités que je ne veux plus ?

Il ne peuvent être supprimer que si le Rfplayer n'est pas reconnu ! sinon existe des bidouilles dans `.storage`, mais pas recommandé.
Procédure:
![image](https://github.com/Doubledom45/HA-2024.3-RFPLAYER/assets/97252459/c21cbe35-f555-483f-893c-90b3d859291c)
## tout est indisponible !
![image](https://github.com/Doubledom45/HA-2024.3-RFPLAYER/assets/97252459/7069ed55-22dc-4618-8e9b-dcfa9add0baa)

Sélection de celui que l'on ne veut plus ! 
![image](https://github.com/Doubledom45/HA-2024.3-RFPLAYER/assets/97252459/152c1072-71f2-477c-9797-dc8d08f1dd04)

# Ensuite redémarrage de HA , obligatoire !

**Comment by mupfpilou** [comment]
Ça ne fonctionne pas pour retirer les entités
Après le reboot j'ai de nouveau des entités RTS Cover-Ax qui apparaissent

Si ya un fichier qui décrit en yaml les entités, je peux essayer de regarder si tu me dis où il est

Je confirme que quand je crée une entité en appelant le service send command avec DIM, l'entité fonctionne
Si je crée l'entité en appelant le service send command avec ON ou OFF, l'entité est créée mais on ne peut pas stop le volet

Enfin, quand je reboot ha, l'intégration est toujours en erreur de configuration
Il faut un autre reboot pour que ça soit ok

J'upload les logs dès que je suis à la maison

**Comment by Doubledom45** [comment]
Attention il faut avoir la bonne version !
J'ai modifier le Reload dans une version d'ailleurs ! le dernier commit 
![image](https://github.com/Doubledom45/HA-2024.3-RFPLAYER/assets/97252459/ecee9155-598c-4ebe-8977-6197b28e5255)

**Comment by mupfpilou** [comment]
Oui, je suis bien en a55c463 sur ce dépôt

**Comment by Doubledom45** [comment]
>Ça ne fonctionne pas pour retirer les entités
Après le reboot j'ai de nouveau des entités RTS Cover-Ax qui apparaissent

Je vais regardé cela

**Comment by Doubledom45** [comment]
@mupfpilou 
>Si je crée l'entité en appelant le service send command avec ON ou OFF, l'entité est créée mais on ne peut pas stop le volet

Est-ce que tu as pu modifier le DIM comme demandé ! dans ton fichier ? et faire le test ?

>Je pense bug avec DIM-ADDON dans rfplayer/rflib/rfpprotocol.py

>👁‍🗨def send_command
remplacer %50 par %4
----------------->
            DIM_ADDON=""
            if command == "DIM" :
                DIM_ADDON="%50" ⛔👉 DIM_ADDON="%4"✅

**Comment by mupfpilou** [comment]
Je teste ca ce WE !
