### ISSUE TITLE
RFPlayer detection issue on HA Yellow POE

### ISSUE THREAD

**Issue by chma31** [Doubledom45/HA-2024.3-RFPLAYER#4]
Hello,

Thanks for all this work. This is great.
The initial issue I have is related to a potential incompatibility of the RFPlayer stick with the Home Assistant Yellow HW with POE. It works perfectly with Home Assistant Yellow Basic (w/o POE) but is not found with the POE version though the HW version is the same (besides the POE components populated), the jumpers are in the same position... the Home Assistant OS the same version...
I saw that on the POE version the /dev/ttyUSB0 driver is missing and I didn't find out up to now how to solve it.

The only difference between my 2 HW is the OS which came already installed on the basic Yellow version when I bought it, tough I installed it by my own from the offical repositery on the POE version.

I am waiting to be able to open a ticket on the Home Assitant forum but meanwhile I identified a potential limitation on this integration :
It creates the device whether or not the RFPlayer is plugged, identified or not.
In my particular case it uses the /dev/ttyAMA2 but doesn't state "RFPlayer - RFPLayer, s/n xxxxx - Ziblue" like described in your doc.

Regards
Christian

**Comment by Doubledom45** [comment]
Salut..
Possible en Français ?
Tu as quoi dans Ha configuration matériel ? HA/config/hardware
Il faut que je vois pourquoi le Yellow ne traduit pas le port USB, normalement c'est L'UART qui fait la gestion à travers le serial_adapter, problème de la puce CM4

**Comment by chma31** [comment]
Bonjour,effectivement j'avais un problème de connexion du module CM4. Je m'en suis aperçu par hasard en appuyant sur le radiateur après avoir créé le ticket sous Github. J'ai rajouté une note en disant que ce problème là (le plus gênant pour moi) était résolu. Désolé pour cette erreur de ma part.Par contre, au cours de tous mes essais pour essayer de comprendre pourquoi cela ne fonctionnait pas sur le Yellow POE, je me suis aperçu que même si aucun RFPlayer n'était inséré, l'intégration propose de connecter un des 3 ports séries et surtout rajoute quand même un appareil, cf photos. Cela me paraît au minimum surprenant.Cordialementenvoyé : 3 mai 2024 à 12:13de : Doubledom ***@***.***>à : "Doubledom45/HA-2024.3-RFPLAYER" ***@***.***>cc : chma31 ***@***.***>, Author ***@***.***>objet : Re: [Doubledom45/HA-2024.3-RFPLAYER] RFPlayer detection issue on HA Yellow POE (Issue #4) Salut.. Possible en Français ? Tu as quoi dans Ha configuration matériel ? HA/config/hardware Il faut que je vois pourquoi le Yellow ne traduit pas le port USB, normalement c'est L'UART qui fait la gestion à travers le serial_adapter, problème de la puce CM4—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
